version: '3.2'

services:
  redis:
    image: redis
    container_name: queue
    restart: always
    ports:
      - '9001:6379'
  db:
    image: mysql:5.7.32
    container_name: appsDB
    restart: always
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
    volumes:
      - ./data/db:/var/lib/mysql

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
