server:
  port: 3001
redis:
  host: 'localhost'
  port: 9001
db:
  type: 'mysql'
  port: 6603
  username: 'root'
  password: 'helloworld'
  database: 'notifications_saas'
  host: 'localhost'
jwt:
  session:
    expiresIn: 36000
    secret: 'developmentSecret'
  apps:
    expiresIn: 360000
    secret: 'developmentappSecret'
email:
  from: \"Suchana\" <app@suchana.com>
  host: smtp.ethereal.email
  port: 587
  auth:
    user: alverta.king@ethereal.email
    pass: DrMYFnk7CTUmsBchvt
