export const NEW_NOTIFICATION_CREATED = 'NEW_NOTIFICATION_CREATED';
export const NEW_AUDEINCE_CREATED = 'NEW_AUDEINCE_CREATED';
export const NEW_APP_CREATED = 'NEW_APP_CREATED';
export const APP_UPDATED = 'APP_UPDATED';
